development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:112ea53f1d72706cc5427d83cdf74dc9@crestfish.redistogo.com:11993/
  # channel_prefix: game_room_production
